### ISSUE TITLE
Parser breaks when .NET 9 SDK is installed.

### ISSUE THREAD

**Issue by marcin-przywoski** [AvaloniaUI/SolutionParser#5]
Avalonia VS Code extension is breaking if the .NET 9 SDK is installed. 

I fixed it by compiling the parser with .NET 9 instead of .NET 8. Works for projects on older version of .NET as well.

**Comment by prashantvc** [comment]
Thank you, could you send a PR

**Comment by dabbinavo** [comment]
@marcin-przywoski I think this has to be fixed in the https://github.com/AvaloniaUI/AvaloniaVSCode repository as the build is triggered there. See https://github.com/AvaloniaUI/AvaloniaVSCode/issues/145#issuecomment-2516479617
